// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: transport/grpc/deck.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeckOpened represents a opened deck of cards.
type DeckOpened struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Shuffled  bool    `protobuf:"varint,2,opt,name=shuffled,proto3" json:"shuffled,omitempty"`
	Remaining uint32  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Cards     []*Card `protobuf:"bytes,4,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *DeckOpened) Reset() {
	*x = DeckOpened{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_deck_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckOpened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckOpened) ProtoMessage() {}

func (x *DeckOpened) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_deck_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckOpened.ProtoReflect.Descriptor instead.
func (*DeckOpened) Descriptor() ([]byte, []int) {
	return file_transport_grpc_deck_proto_rawDescGZIP(), []int{0}
}

func (x *DeckOpened) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeckOpened) GetShuffled() bool {
	if x != nil {
		return x.Shuffled
	}
	return false
}

func (x *DeckOpened) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *DeckOpened) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

// DeckClosed represents a closed deck of cards.
type DeckClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Shuffled  bool   `protobuf:"varint,2,opt,name=shuffled,proto3" json:"shuffled,omitempty"`
	Remaining uint32 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
}

func (x *DeckClosed) Reset() {
	*x = DeckClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_deck_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckClosed) ProtoMessage() {}

func (x *DeckClosed) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_deck_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckClosed.ProtoReflect.Descriptor instead.
func (*DeckClosed) Descriptor() ([]byte, []int) {
	return file_transport_grpc_deck_proto_rawDescGZIP(), []int{1}
}

func (x *DeckClosed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeckClosed) GetShuffled() bool {
	if x != nil {
		return x.Shuffled
	}
	return false
}

func (x *DeckClosed) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

// Card represents a single card.
type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Suit  string `protobuf:"bytes,2,opt,name=suit,proto3" json:"suit,omitempty"`
	Code  string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_deck_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_deck_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_transport_grpc_deck_proto_rawDescGZIP(), []int{2}
}

func (x *Card) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Card) GetSuit() string {
	if x != nil {
		return x.Suit
	}
	return ""
}

func (x *Card) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_transport_grpc_deck_proto protoreflect.FileDescriptor

var file_transport_grpc_deck_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x64, 0x65, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x78, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x6b, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x73, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x05, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x56, 0x0a, 0x0a, 0x44,
	0x65, 0x63, 0x6b, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x75,
	0x66, 0x66, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x68, 0x75,
	0x66, 0x66, 0x6c, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x22, 0x44, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x75, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x75, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x67, 0x6a, 0x75, 0x6c, 0x65, 0x73, 0x2f,
	0x64, 0x65, 0x63, 0x6b, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transport_grpc_deck_proto_rawDescOnce sync.Once
	file_transport_grpc_deck_proto_rawDescData = file_transport_grpc_deck_proto_rawDesc
)

func file_transport_grpc_deck_proto_rawDescGZIP() []byte {
	file_transport_grpc_deck_proto_rawDescOnce.Do(func() {
		file_transport_grpc_deck_proto_rawDescData = protoimpl.X.CompressGZIP(file_transport_grpc_deck_proto_rawDescData)
	})
	return file_transport_grpc_deck_proto_rawDescData
}

var file_transport_grpc_deck_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transport_grpc_deck_proto_goTypes = []interface{}{
	(*DeckOpened)(nil), // 0: grpc.DeckOpened
	(*DeckClosed)(nil), // 1: grpc.DeckClosed
	(*Card)(nil),       // 2: grpc.Card
}
var file_transport_grpc_deck_proto_depIdxs = []int32{
	2, // 0: grpc.DeckOpened.cards:type_name -> grpc.Card
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transport_grpc_deck_proto_init() }
func file_transport_grpc_deck_proto_init() {
	if File_transport_grpc_deck_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transport_grpc_deck_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckOpened); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_deck_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeckClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_deck_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transport_grpc_deck_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_grpc_deck_proto_goTypes,
		DependencyIndexes: file_transport_grpc_deck_proto_depIdxs,
		MessageInfos:      file_transport_grpc_deck_proto_msgTypes,
	}.Build()
	File_transport_grpc_deck_proto = out.File
	file_transport_grpc_deck_proto_rawDesc = nil
	file_transport_grpc_deck_proto_goTypes = nil
	file_transport_grpc_deck_proto_depIdxs = nil
}
