name: goreleaser

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      -
        name: Set up extra tools
        run: |
          go install github.com/magefile/mage@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GR_GH_TOKEN }}
